### ISSUE TITLE
Azure Webjob alternative

### ISSUE THREAD

**Issue by mizzunet** [ytechie/kindle-rss#1]
Sir, I'm a student and I do not own a CC for Azure billing. So could you tell if it's possible to make it work by cron job on GitHub Actions Workflow or Heroku?

**Comment by ytechie** [comment]
I don't see why it wouldn't work. I haven't run the code in years, but I don't see anything specifically forcing it to only work on Azure Functions.

You might have to replace SendGrid as well. I'm not sure if you can use it without a credit card.
